---
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "example" > example.txt
          echo "filename=example.txt" >> $GITHUB_OUTPUT

      - name: Save example.txt
        uses: actions/upload-artifact@v3
        with:
          name: example.txt
          path: .
          if-no-files-found: error
          